export const BASE_URL = "https://localhost:7033/api/v1"

export const ENDPOINTS = {
    Register: BASE_URL + "/Auth/register",
    Login: BASE_URL + "/Auth/login",
    UploadFile: BASE_URL + '/Plant/Create',
    UploadCalendar: BASE_URL + '/Calendar/create',
    Days: BASE_URL + '/Calendar/{id}/days',
    UpdateDayStatus: BASE_URL + '/Calendar/{dayId}/update',
    Data: BASE_URL + '/Chart/{id}/{city}/data',
    AddCity: BASE_URL + '/Chart/AddCity',
    Reminder: BASE_URL + '/Home/{id}/days',
    Alert: BASE_URL + '/Home/{id}/{city}/alert',
    Late: BASE_URL + '/Home/{id}/latedays',
    UpdateLDay: BASE_URL + '/Home/{dayId}/updatelateday',
    UploadSensorType: BASE_URL + '/Device/createSensorType',
    GetSensorType: BASE_URL + '/Device/getSensorType',
    UploadDevice: BASE_URL + '/Device/{id}/register-device',
    GetDevice: BASE_URL + '/Plant/{id}/getDevice',
    GetPlantProfiles: BASE_URL + '/Plant/getPlantProfiles',
    UploadProfileType: BASE_URL + '/Plant/createPlantProfile',
    GetPlants: BASE_URL + '/Plants/{id}/getPlants',
    GetImage: BASE_URL + '/Plants/{name}/Image',
    UploadCondition: BASE_URL + '/Plant/createCondition',
    GetInactivePlants: BASE_URL + '/Diary/{id}/getPlants',
    GetInActiveDays: BASE_URL + '/Diary/{id}/days',
    CreateDiary: BASE_URL + '/Diary/CreateDiary',
    GetDiaries: BASE_URL + '/Diary/{userId}/diaries',
    GetInActiveDiaryDays: BASE_URL + '/Diary/{id}/Diarydays',
    GetInactiveDiaryPlants: BASE_URL + '/Diary/{id}/getDiaryPlants',
    UpdatePlantStatus: BASE_URL + '/Plants/{id}/updatePlant',
}